name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          yarn install
          yarn build
      - run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
      - run: |
          jq . manifest.json
      - uses: actions/upload-artifact@v2
        with:
          name: lhci
          path: lhci
